image: python:3.12.7-bookworm

pages:
  stage: deploy
  script:
    - pip3 install -r requirements.txt
    #- apt-get install -y fonts-ipafont fonts-ipaexfont
    - make html
    - mkdir -p public/
    - cp -r build/html/* public/
  artifacts:
    paths:
      - public
  only:
    - main

